PSD-99 Add 'proof' to vuln info
asecurityteam/nexpose-vuln-filter pull request #14
Opened 2019-09-17 13:38 UTC by LorenBoren

This change adds the "proof" field to the incoming and outgoing schema for Vulnerability Details so we can expose "proof" information in Nexpose VULN tickets.

2019-09-17 19:21 UTC, genuinebrandonchan commented
Do you not need to add a proof field to the code for unmarshalling?

2019-09-17 19:25 UTC, genuinebrandonchan commented
do you mind changing team owners to prodsecdev within CODEOWNERS?

2019-09-17 20:35 UTC, faldridge requested changes
Task: add `Proof` field to both the domain struct and the handler struct with JSON annotations.

2019-09-18 14:08 UTC, faldridge approved these changes

2019-09-18 16:21 UTC, fakebrandonchan approved these changes

2019-09-18 16:22 UTC, merged