changed schemas to reflect scanTime change instead of lastScanned
asecurityteam/nexpose-vuln-filter pull request #18
Opened 2019-11-26 19:02 UTC by originalbchan

dependent on https://github.com/asecurityteam/nexpose-asset-producer/pull/36/files

2019-11-26 19:27 UTC, mikerott requested changes
Similar to the comment I made in https://github.com/asecurityteam/nexpose-asset-producer/pull/36/files -- can we preserve the `lastScanned` property and add the `scanTime` then use whichever one is non-zero value.  This makes the change backward compatible and safe during the corresponding change of the schema in the other services.

2019-11-27 22:27 UTC, mikerott commented on gateway-incoming.yaml
> -        - lastScanned
task:  should `scanTime` be among the required?

2019-11-27 22:27 UTC, mikerott commented on gateway-incoming.yaml
> -        - lastScanned
task:  should `scanTime` be among the required?

2019-11-27 22:27 UTC, mikerott commented on gateway-outgoing.yaml
> -        - lastScanned
task:  should `scanTime` be among the required?

2019-11-27 22:33 UTC, mikerott approved these changes
Task:  I expected to see code changes that took the inbound `scanTime` and set it on the outbound `lastScanned` and the inverse when the prior service only sends one of the two values.  I don't see any code like that in the PR.  I'm approving this with much fear.

2019-12-02 14:44 UTC, faldridge approved these changes

2019-12-02 15:45 UTC, merged